### ISSUE TITLE
Concealment based on ownership status

### ISSUE THREAD

**Issue by Death666Machine** [TorchAPI/Concealment#14]
Would it be possible to conceal grids who's owner or faction members is not currently logged in? Only concern being another player building onto of another, but likelyhood of that is pretty slim

**Comment by Jimmacle** [comment]
Theoretically yes, but grids always have to be revealed if any player gets close to them otherwise it'll cause bad behavior.

**Comment by Death666Machine** [comment]
Ahh, I see was just a random idea I had. Ty for the quick response
