### ISSUE TITLE
Client crash 

### ISSUE THREAD

**Issue by ruffst** [TorchAPI/Concealment#23]
The client crashes when leaving the cockpit.

This occurred immediately after the plug-in update on our old Map.

It took several attempts to isolate concealment as the cause. Even after a fresh Torch installation using a new map the plugin crashes the game.

**Comment by rexxar-tc** [comment]
Logs or it didn't happen

**Comment by ruffst** [comment]
so thats as simple way to avoid work ;-P Nevermind. There is no log to report because Torch just said that the user disconnected. Nothing more. The client just crashed bevore. After removing concealment it worked fine. Putting it in back again. Client crash.

**Comment by Jimmacle** [comment]
There should be a log from the client that crashed in that case.

**Comment by ruffst** [comment]
It has unfortunatly just some hours back. Ill try to reproduce it

**Comment by ruffst** [comment]
Saw that there was a recent update for Torch and concealment. so i just reloaded the plugin. Now it seems to work. The clients are not crashing anymore. Whatever it was, it seems to be over. Thanks for your patience :-)
