### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by Jemixam** [TorchAPI/Concealment#5]
PluginManager: Item 'D:\SteamCMD\SpaceEngineerDedicatedServer\Plugins\Concealment-master' is missing a manifest, skipping update check.

PluginManager: Item 'D:\SteamCMD\SpaceEngineerDedicatedServer\Plugins\Concealment-master' is missing a manifest, skipping.

Why?

**Comment by mccorkle** [comment]
Just guessing that you don't have the concealment manifest.xml in your DedicatedServer64/Plugins/Concealment folder.  

I think you can get that from the zip file packages on Jenkins.

**Comment by Jemixam** [comment]
thx

**Comment by Jemixam** [comment]
20:10:25.1392 [ERROR]  PluginManager: Unable to find archive for the latest release of 'TorchAPI/Concealment.'
20:10:25.1392 [ERROR]  PluginManager: Unable to find archive for the latest release of 'TorchAPI/Essentials.'

other problem :/

**Comment by szczepix** [comment]
it's still in progress feature that is like Warning for you now

**Comment by Jemixam** [comment]
it gonna work?
