### ISSUE TITLE
Implement documentation

### ISSUE THREAD

**Issue by JabDoesThings** [TorchAPI/Concealment#8]
Please implement documentation that explains each configured setting and how to approach the setting with information provided such as value range, and any notes for special values or states set for each setting. This plug-in looks to be developed for private use, and with being open sourced and available to the public, a lack of documentation makes it very hard to approach the plug-in and utilize the plug-in properly and at efficiency.

**Comment by mccorkle** [comment]
@JabJabJab What kind of documentation are you looking for?  Concealment is a plugin that runs inside of the Torch Dedicated Server manager (which itself implements the Space Engineers Dedicated Server).  

The settings and behavior of the plugin is managed via the GUI (image attached).  What questions do you have which would need documentation?  

![screenshot 2017-12-05 16 25 37](https://user-images.githubusercontent.com/2091058/33631571-fb1ff8dc-d9d8-11e7-82ca-0a77fdce273d.png)

**Comment by JabJabJab** [comment]
@mccorkle Hello.

The settings can have tool-tips, or short summaries of what they are for, and any additional information regarding the limits of the settings, such as value range for numerical input fields.

E.G: Conceal Distance -> "The maximum distance for a grid to be active for a player. (min: 200, max: 100000)"

Of course those limits aren't actually what the limits are set to in the code, but just as an example. This would help out a lot for people who may not have an eye to see what's going on behind the menu.

**Comment by mccorkle** [comment]
Perhaps you could draft up a document in the format you are imagining, include your assumptions about what each of the fields do and share it with the Torch discord #plugins room on https://discord.gg/VP4gjWU.  Those of us that use Torch every day could help fill in any gaps.
